version: '3.9'

services:
  # Serviço MongoDB
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db

  # Serviço da API Node.js
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodeapp
    container_name: api
    ports:
      - 3030:3030
    depends_on:
      - mongo_db

volumes:
  mongo_data: {}