version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodeapp
    container_name: api
    ports:
      - 3030:3030
    depends_on:
      - mongo_db
    networks:
      - app-network

  sentiment:
    build:
      context: ../djangoapp/microservices
    ports:
      - 5050:5000
    container_name: sentiment
    networks:
      - app-network

volumes:
  mongo_data: {}

networks:
  app-network:
    driver: bridge